version: "1.0"

# Docker Compose khusus untuk Frontend (Next.js)
# Usage: docker-compose -f docker-compose.frontend.yml up -d

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_CLOUDINARY_URL="https://res.cloudinary.com/df4uc8lio/"
        - NEXT_PUBLIC_API_URL=https://api.bantuin-campus.me/api
        - NEXT_PUBLIC_SOCKET_URL=https://api.bantuin-campus.me/api
        - NEXT_PUBLIC_MIDTRANS_CLIENT_KEY=SB-Mid-client-axYadAcc6Nog-Rtg
    container_name: bantuin-frontend
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      NEXT_PUBLIC_CLOUDINARY_URL: https://res.cloudinary.com/df4uc8lio/
      NESTJS_API_URL: https://api.bantuin-campus.me/api
      NEXT_PUBLIC_API_URL: https://api.bantuin-campus.me/api
      NEXT_PUBLIC_SOCKET_URL: https://api.bantuin-campus.me/api
      NEXT_PUBLIC_MIDTRANS_CLIENT_KEY: SB-Mid-client-axYadAcc6Nog-Rtg
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  bantuin-frontend-network:
    driver: bridge
